# Generated by Django 4.1.3 on 2022-12-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appuno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('codigo', models.IntegerField()),
                ('categoria', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=30)),
                ('altura', models.IntegerField()),
            ],
        ),
    ]
